config/routes.rb
Chevy::Application.routes.draw do
  root :to => 'pages#home'

  get "pages/home"

  get 'phaseone' => 'pages#phaseone'

  get 'phasetwo' => 'pages#phasetwo'

  get 'phasethree' => 'pages#phasethree'

  get 'team' => 'pages#team'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def phaseone
  end

  def phasetwo
  end

  def phasethree
  end

  def team
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <a class="brand" href="/">My Nova Project</a>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Home',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'Phase One',  phaseone_path %>
                        </li>
                        <li>    
                            <%= link_to 'Phase Two',  phasetwo_path %>
                        </li>
                        <li>    
                            <%= link_to 'Phase Three',  phasethree_path %>
                        </li>
                        <li>    
                            <%= link_to 'The Team',  team_path %>
                        </li>
                    </ul>
                    
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Nova Project</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="slide">

	<center><h2>Nova Project Journal</h2>

	<h3>September 2, 2013</h3>
	<h4>Dennis Keefe</h4>
    
    <a href="http://s169.photobucket.com/user/dkeefe75/media/Nova%202013/photo14.jpg.html" target="_blank"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/Nova%202013/photo14.jpg" width="450" height="450" border="0" alt="Chevy 350 4 bolt photo photo14.jpg"/></a>
    	<hr>
    	
    <p>Well, so much for starting on the 1st of September, the insane amount of rain we have been having caused a slight delay. I wasn't able to move the car into the shop because of some other vehicles that have not yet been moved out. I couldn't get what I needed done outside due to the weather, but I did do some inventory and planning. I have a fresh small block Chevy 350 4 bolt, that has been bored .30 over. This is great, because my original plan was to pull a 350 from an old truck my father-in-law had, until he offered me this new one. I have a fresh set of Votec heads, but will need to buy a new intake to match the heads.
    </p>

    
    <p>My father-in-law found these great new wheels with very new tires on them. He though they were for a Chevy, but turns out they are Ford. I think they would look great on the Nova, so I will put a Mustang rear end under it and modify the front suspension to be able to use them. There is a lot of work ahead, but I know that it will be a lot of fun, especially as the weather cools and we head into fall.
 
     </p>

    
</div>

app/views/pages/phaseone.html.erb
<div class="container-fluid">
<div class="row-fluid">
<div class="span12">

    <div class="page-header">
        <h3>Gallery</h3>
        <p>1972 Chevy Nova Phase One</p>
    </div>
        
    <div class="carousel slide" id="myCarousel">
        <div class="carousel-inner">
            <div class="item active">
                    <ul class="thumbnails">
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/Nova%202013/photo15.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>September 2, 2013</h4>
                                <p>New set of wheels</p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/Nova%202013/photo14.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>September 2, 2013</h4>
                                <p>350 small block Chevy .30 over</p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/Nova%202013/photo16.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>September 2013</h4>
                                <p>After being neglected for 6 years</p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/Nova%202013/photo17.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>September 2013</h4>
                                <p></p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                    </ul>
              </div><!-- /Slide1 --> 
            <div class="item">
                    <ul class="thumbnails">
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/DSC02618.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>May 7, 2007</h4>
                				<p>Just getting started</p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/DSC02631.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>May 7, 2007</h4>
                				<p>Right fender repair</p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/DSC02655.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>May 13, 2007</h4>
                				<p>Left tail lamp area</p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/DSC02654.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>May 13, 2007</h4>
                				<p>Right tail lamp area</p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                    </ul>
              </div><!-- /Slide2 --> 
            <div class="item">
                    <ul class="thumbnails">
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/DSC02653.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>May 13, 2013</h4>
                				<p>Right quarter panel</p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/DSC02698.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>May 28, 2007</h4>
                				<p>Inner fenders, sand bblasted and sealed with DP90</p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/DSC02785.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>June 29, 2007</h4>
                				<p>Radiator support, sand blasted and sealed with DP90</p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                        <li class="span3">
                            <div class="thumbnail">
                                <a href="#"><img src="http://i169.photobucket.com/albums/u229/dkeefe75/Nova%202013/photo15.jpg" alt=""></a>
                            </div>
                            <div class="caption">
                                <h4>September 2, 2013</h4>
                				<p>New set of wheels</p>
                                <a class="btn btn-mini" href="#">&raquo; Read More</a>
                            </div>
                        </li>
                    </ul>
              </div><!-- /Slide3 --> 

              <div class="item">
                    <ul class="thumbnails">
                        
                    </ul>
              </div>
        </div>
        
        <div class="control-box">                            
            <a data-slide="prev" href="#myCarousel" class="carousel-control left">‹</a>
            <a data-slide="next" href="#myCarousel" class="carousel-control right">›</a>
        </div><!-- /.control-box -->   
                              
    </div><!-- /#myCarousel -->
        
</div><!-- /.span12 -->          
</div><!-- /.row --> 
</div><!-- /.container -->

                            
<!-- Delete This -->                        
   
</div>

app/views/pages/phasethree.html.erb
<center><h1>Be patient!</h1>

app/views/pages/phasetwo.html.erb
<center><h1>Come on, give me time to finish phase one!</h1>

app/views/pages/team.html.erb
<div class="imgwrap">
  <div class="imgContainer">
    <img src="http://imageshack.us/a/img33/5462/42082647465194256835615.jpg" alt="DTE" />
  </div>
  <div class="imgContainer">
    <img src="http://imageshack.us/a/img203/8784/x9wi.png" alt="DTE" />
  </div>
    <div class="imgContainer">
    <img src="http://imageshack.us/a/img839/2866/dqnc.png" alt="DTE" />
  </div>
    
</div>
<div>

</div>
<center>
	<h2>
	Restoration begins on September 1, 2013.
</h2>